/// Flutter icons Pets
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Pets
///      fonts:
///       - asset: fonts/Pets.ttf
///
///
///
import 'package:flutter/widgets.dart';

import 'package:flutter/material.dart';
//Icons made by "https://www.flaticon.com/authors/freepik"

class Tasks {
  Tasks._();

  static const _kFontFam = 'Tasks';

  static const IconData groceries = Icons.local_grocery_store;
}
